// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Services/BDIDecisionProcessService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService {
  public static partial class BDIDecisionProcessService
  {
    static readonly string __ServiceName = "FSR.DigitalTwin.App.GRPC.BDIDecisionProcessService";

    static readonly grpc::Marshaller<global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest> __Marshaller_FSR_DigitalTwin_App_GRPC_RunDecisionProcessRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::FSR.DigitalTwin.App.GRPC.Process.BDI.ActionDTO> __Marshaller_FSR_DigitalTwin_App_GRPC_ActionDTO = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FSR.DigitalTwin.App.GRPC.Process.BDI.ActionDTO.Parser.ParseFrom);

    static readonly grpc::Method<global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest, global::FSR.DigitalTwin.App.GRPC.Process.BDI.ActionDTO> __Method_RunDecisionProcess = new grpc::Method<global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest, global::FSR.DigitalTwin.App.GRPC.Process.BDI.ActionDTO>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RunDecisionProcess",
        __Marshaller_FSR_DigitalTwin_App_GRPC_RunDecisionProcessRequest,
        __Marshaller_FSR_DigitalTwin_App_GRPC_ActionDTO);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.BDIDecisionProcessServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of BDIDecisionProcessService</summary>
    [grpc::BindServiceMethod(typeof(BDIDecisionProcessService), "BindService")]
    public abstract partial class BDIDecisionProcessServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::FSR.DigitalTwin.App.GRPC.Process.BDI.ActionDTO> RunDecisionProcess(global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for BDIDecisionProcessService</summary>
    public partial class BDIDecisionProcessServiceClient : grpc::ClientBase<BDIDecisionProcessServiceClient>
    {
      /// <summary>Creates a new client for BDIDecisionProcessService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BDIDecisionProcessServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BDIDecisionProcessService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BDIDecisionProcessServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BDIDecisionProcessServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BDIDecisionProcessServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::FSR.DigitalTwin.App.GRPC.Process.BDI.ActionDTO RunDecisionProcess(global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RunDecisionProcess(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::FSR.DigitalTwin.App.GRPC.Process.BDI.ActionDTO RunDecisionProcess(global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RunDecisionProcess, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::FSR.DigitalTwin.App.GRPC.Process.BDI.ActionDTO> RunDecisionProcessAsync(global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RunDecisionProcessAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::FSR.DigitalTwin.App.GRPC.Process.BDI.ActionDTO> RunDecisionProcessAsync(global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RunDecisionProcess, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BDIDecisionProcessServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BDIDecisionProcessServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BDIDecisionProcessServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RunDecisionProcess, serviceImpl.RunDecisionProcess).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, BDIDecisionProcessServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RunDecisionProcess, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest, global::FSR.DigitalTwin.App.GRPC.Process.BDI.ActionDTO>(serviceImpl.RunDecisionProcess));
    }

  }
}
#endregion
