//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FsrMoveit
{
    [Serializable]
    public class MoveServiceResponse : Message
    {
        public const string k_RosMessageName = "fsr_moveit/MoveService";
        public override string RosMessageName => k_RosMessageName;

        public Moveit.RobotTrajectoryMsg trajectory;

        public MoveServiceResponse()
        {
            this.trajectory = new Moveit.RobotTrajectoryMsg();
        }

        public MoveServiceResponse(Moveit.RobotTrajectoryMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static MoveServiceResponse Deserialize(MessageDeserializer deserializer) => new MoveServiceResponse(deserializer);

        private MoveServiceResponse(MessageDeserializer deserializer)
        {
            this.trajectory = Moveit.RobotTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "MoveServiceResponse: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
