//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FsrMoveit
{
    [Serializable]
    public class MoveServiceRequest : Message
    {
        public const string k_RosMessageName = "fsr_moveit/MoveService";
        public override string RosMessageName => k_RosMessageName;

        public MoveitJointsMsg joints_input;
        public MoveitGroupMsg group;
        public MoveInputMsg pars;

        public MoveServiceRequest()
        {
            this.joints_input = new MoveitJointsMsg();
            this.group = new MoveitGroupMsg();
            this.pars = new MoveInputMsg();
        }

        public MoveServiceRequest(MoveitJointsMsg joints_input, MoveitGroupMsg group, MoveInputMsg pars)
        {
            this.joints_input = joints_input;
            this.group = group;
            this.pars = pars;
        }

        public static MoveServiceRequest Deserialize(MessageDeserializer deserializer) => new MoveServiceRequest(deserializer);

        private MoveServiceRequest(MessageDeserializer deserializer)
        {
            this.joints_input = MoveitJointsMsg.Deserialize(deserializer);
            this.group = MoveitGroupMsg.Deserialize(deserializer);
            this.pars = MoveInputMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints_input);
            serializer.Write(this.group);
            serializer.Write(this.pars);
        }

        public override string ToString()
        {
            return "MoveServiceRequest: " +
            "\njoints_input: " + joints_input.ToString() +
            "\ngroup: " + group.ToString() +
            "\npars: " + pars.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
