// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Services/BDIDecisionProcessService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService {

  /// <summary>Holder for reflection information generated from Protos/Services/BDIDecisionProcessService.proto</summary>
  public static partial class BDIDecisionProcessServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/Services/BDIDecisionProcessService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BDIDecisionProcessServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci9Qcm90b3MvU2VydmljZXMvQkRJRGVjaXNpb25Qcm9jZXNzU2VydmljZS5w",
            "cm90bxIYRlNSLkRpZ2l0YWxUd2luLkFwcC5HUlBDGhFQcm90b3MvQmFzZS5w",
            "cm90bxoaUHJvdG9zL0RUTy9CRElNb2RlbHMucHJvdG8iJwoZUnVuRGVjaXNp",
            "b25Qcm9jZXNzUmVxdWVzdBIKCgJpZBgBIAEoCTKLAQoZQkRJRGVjaXNpb25Q",
            "cm9jZXNzU2VydmljZRJuChJSdW5EZWNpc2lvblByb2Nlc3MSMy5GU1IuRGln",
            "aXRhbFR3aW4uQXBwLkdSUEMuUnVuRGVjaXNpb25Qcm9jZXNzUmVxdWVzdBoj",
            "LkZTUi5EaWdpdGFsVHdpbi5BcHAuR1JQQy5BY3Rpb25EVE9CSqoCR0ZTUi5E",
            "aWdpdGFsVHdpbi5BcHAuR1JQQy5Qcm9jZXNzLkJESS5TZXJ2aWNlcy5CRElE",
            "ZWNpc2lvblByb2Nlc3NTZXJ2aWNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::FSR.DigitalTwin.App.GRPC.BaseReflection.Descriptor, global::FSR.DigitalTwin.App.GRPC.Process.BDI.BDIModelsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest), global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.RunDecisionProcessRequest.Parser, new[]{ "Id" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RunDecisionProcessRequest : pb::IMessage<RunDecisionProcessRequest> {
    private static readonly pb::MessageParser<RunDecisionProcessRequest> _parser = new pb::MessageParser<RunDecisionProcessRequest>(() => new RunDecisionProcessRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RunDecisionProcessRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.DigitalTwin.App.GRPC.Process.BDI.Services.BDIDecisionProcessService.BDIDecisionProcessServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RunDecisionProcessRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RunDecisionProcessRequest(RunDecisionProcessRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RunDecisionProcessRequest Clone() {
      return new RunDecisionProcessRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RunDecisionProcessRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RunDecisionProcessRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RunDecisionProcessRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
