//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FsrMoveit
{
    [Serializable]
    public class MoveInputMsg : Message
    {
        public const string k_RosMessageName = "fsr_moveit/MoveInput";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg target_pose;
        public double max_velocity;
        public double max_acceleration;

        public MoveInputMsg()
        {
            this.target_pose = new Geometry.PoseMsg();
            this.max_velocity = 0.0;
            this.max_acceleration = 0.0;
        }

        public MoveInputMsg(Geometry.PoseMsg target_pose, double max_velocity, double max_acceleration)
        {
            this.target_pose = target_pose;
            this.max_velocity = max_velocity;
            this.max_acceleration = max_acceleration;
        }

        public static MoveInputMsg Deserialize(MessageDeserializer deserializer) => new MoveInputMsg(deserializer);

        private MoveInputMsg(MessageDeserializer deserializer)
        {
            this.target_pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.max_velocity);
            deserializer.Read(out this.max_acceleration);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_pose);
            serializer.Write(this.max_velocity);
            serializer.Write(this.max_acceleration);
        }

        public override string ToString()
        {
            return "MoveInputMsg: " +
            "\ntarget_pose: " + target_pose.ToString() +
            "\nmax_velocity: " + max_velocity.ToString() +
            "\nmax_acceleration: " + max_acceleration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
