//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FsrMoveit
{
    [Serializable]
    public class MoveitGroupMsg : Message
    {
        public const string k_RosMessageName = "fsr_moveit/MoveitGroup";
        public override string RosMessageName => k_RosMessageName;

        public string group_name;
        public string end_effector_name;
        public string base_link_name;

        public MoveitGroupMsg()
        {
            this.group_name = "";
            this.end_effector_name = "";
            this.base_link_name = "";
        }

        public MoveitGroupMsg(string group_name, string end_effector_name, string base_link_name)
        {
            this.group_name = group_name;
            this.end_effector_name = end_effector_name;
            this.base_link_name = base_link_name;
        }

        public static MoveitGroupMsg Deserialize(MessageDeserializer deserializer) => new MoveitGroupMsg(deserializer);

        private MoveitGroupMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.group_name);
            deserializer.Read(out this.end_effector_name);
            deserializer.Read(out this.base_link_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.group_name);
            serializer.Write(this.end_effector_name);
            serializer.Write(this.base_link_name);
        }

        public override string ToString()
        {
            return "MoveitGroupMsg: " +
            "\ngroup_name: " + group_name.ToString() +
            "\nend_effector_name: " + end_effector_name.ToString() +
            "\nbase_link_name: " + base_link_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
