//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FsrMoveit
{
    [Serializable]
    public class MoveitJointsMsg : Message
    {
        public const string k_RosMessageName = "fsr_moveit/MoveitJoints";
        public override string RosMessageName => k_RosMessageName;

        public string[] joint_names;
        public double[] joints;
        public Geometry.PoseMsg pick_pose;
        public Geometry.PoseMsg place_pose;

        public MoveitJointsMsg()
        {
            this.joint_names = new string[0];
            this.joints = new double[6];
            this.pick_pose = new Geometry.PoseMsg();
            this.place_pose = new Geometry.PoseMsg();
        }

        public MoveitJointsMsg(string[] joint_names, double[] joints, Geometry.PoseMsg pick_pose, Geometry.PoseMsg place_pose)
        {
            this.joint_names = joint_names;
            this.joints = joints;
            this.pick_pose = pick_pose;
            this.place_pose = place_pose;
        }

        public static MoveitJointsMsg Deserialize(MessageDeserializer deserializer) => new MoveitJointsMsg(deserializer);

        private MoveitJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_names, deserializer.ReadLength());
            deserializer.Read(out this.joints, sizeof(double), 6);
            this.pick_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.place_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joint_names);
            serializer.Write(this.joint_names);
            serializer.Write(this.joints);
            serializer.Write(this.pick_pose);
            serializer.Write(this.place_pose);
        }

        public override string ToString()
        {
            return "MoveitJointsMsg: " +
            "\njoint_names: " + System.String.Join(", ", joint_names.ToList()) +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\npick_pose: " + pick_pose.ToString() +
            "\nplace_pose: " + place_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
