//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FsrMoveit
{
    [Serializable]
    public class PickAndPlaceInputMsg : Message
    {
        public const string k_RosMessageName = "fsr_moveit/PickAndPlaceInput";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pick_pose;
        public Geometry.PoseMsg place_pose;
        public double pick_pose_z;
        public double place_pose_z;
        public double max_velocity;
        public double max_acceleration;

        public PickAndPlaceInputMsg()
        {
            this.pick_pose = new Geometry.PoseMsg();
            this.place_pose = new Geometry.PoseMsg();
            this.pick_pose_z = 0.0;
            this.place_pose_z = 0.0;
            this.max_velocity = 0.0;
            this.max_acceleration = 0.0;
        }

        public PickAndPlaceInputMsg(Geometry.PoseMsg pick_pose, Geometry.PoseMsg place_pose, double pick_pose_z, double place_pose_z, double max_velocity, double max_acceleration)
        {
            this.pick_pose = pick_pose;
            this.place_pose = place_pose;
            this.pick_pose_z = pick_pose_z;
            this.place_pose_z = place_pose_z;
            this.max_velocity = max_velocity;
            this.max_acceleration = max_acceleration;
        }

        public static PickAndPlaceInputMsg Deserialize(MessageDeserializer deserializer) => new PickAndPlaceInputMsg(deserializer);

        private PickAndPlaceInputMsg(MessageDeserializer deserializer)
        {
            this.pick_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.place_pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.pick_pose_z);
            deserializer.Read(out this.place_pose_z);
            deserializer.Read(out this.max_velocity);
            deserializer.Read(out this.max_acceleration);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pick_pose);
            serializer.Write(this.place_pose);
            serializer.Write(this.pick_pose_z);
            serializer.Write(this.place_pose_z);
            serializer.Write(this.max_velocity);
            serializer.Write(this.max_acceleration);
        }

        public override string ToString()
        {
            return "PickAndPlaceInputMsg: " +
            "\npick_pose: " + pick_pose.ToString() +
            "\nplace_pose: " + place_pose.ToString() +
            "\npick_pose_z: " + pick_pose_z.ToString() +
            "\nplace_pose_z: " + place_pose_z.ToString() +
            "\nmax_velocity: " + max_velocity.ToString() +
            "\nmax_acceleration: " + max_acceleration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
