//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/FSR/Scripts/Features/Player/Controls/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace FSR.DigitalTwin.Client.Features.Player.Controls
{
    public partial class @PlayerControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""FirstPersonPlayer"",
            ""id"": ""5fc40a86-de9c-4c8a-963d-247e22422a34"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""93c3b113-e4b4-4b0a-95b8-a641f993a6da"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""3b6f39bd-c3aa-4005-a275-265ab25242bc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""4e391b21-94f4-4871-98e4-1a6b4200a085"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action0"",
                    ""type"": ""Button"",
                    ""id"": ""538d80ca-e819-4cc9-b159-99da4a92c92d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action1"",
                    ""type"": ""Button"",
                    ""id"": ""26e8c690-e997-4037-b4fc-365ab0207f41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Control0"",
                    ""type"": ""Button"",
                    ""id"": ""58d46d0d-e083-46f2-b73e-745a38b87263"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Control1"",
                    ""type"": ""Button"",
                    ""id"": ""10f0f825-cd9e-40cc-a176-9fc71b71839e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""b6650b94-5c3a-48a6-a1fa-b50ece163045"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""daea9360-56de-4a24-8bcf-d2edb85bf021"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1edb1dea-5d31-4682-9eb0-907278c02487"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""eaaea4f5-3c87-4055-86f3-2217b9682ea5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7fccbfe2-ed79-414c-8b42-696a3c8c535a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9e1bc2b6-019e-4d4b-a173-973d410ef2c2"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8dd3600b-8365-4fdf-ada6-5d592a76a0eb"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be38e03e-e699-489a-b253-4c9b816fab19"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b784999b-2eed-44dc-bd56-8acfacb1b360"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8603264-7efe-4d8a-9f21-7e87bb2fa34b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Control1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""970e9cbf-decb-4de4-b663-ae6fef3409aa"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Control0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""945dbb9e-1ee7-4f4f-bb19-2858a52ef7a7"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Control0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FirstPersonHRI"",
            ""id"": ""5ca2fd65-c293-40e1-a551-4bf05c6d7f2b"",
            ""actions"": [
                {
                    ""name"": ""Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""ce45ea1e-76f6-43c5-9522-50d1857897a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab"",
                    ""type"": ""Value"",
                    ""id"": ""5bdfcb0c-56ae-4c1b-9987-03b9138c4461"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Drag"",
                    ""type"": ""Value"",
                    ""id"": ""81dc7c9e-9236-455a-b923-a8e3aa836c46"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""34a51ed7-eaa6-497d-9adc-2a897ae21b15"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80a3e7f5-53cf-4875-90a6-846258b5c4ba"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69026ff9-b25b-4f60-aa8e-3020280e3fdd"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // FirstPersonPlayer
            m_FirstPersonPlayer = asset.FindActionMap("FirstPersonPlayer", throwIfNotFound: true);
            m_FirstPersonPlayer_Move = m_FirstPersonPlayer.FindAction("Move", throwIfNotFound: true);
            m_FirstPersonPlayer_Look = m_FirstPersonPlayer.FindAction("Look", throwIfNotFound: true);
            m_FirstPersonPlayer_Jump = m_FirstPersonPlayer.FindAction("Jump", throwIfNotFound: true);
            m_FirstPersonPlayer_Action0 = m_FirstPersonPlayer.FindAction("Action0", throwIfNotFound: true);
            m_FirstPersonPlayer_Action1 = m_FirstPersonPlayer.FindAction("Action1", throwIfNotFound: true);
            m_FirstPersonPlayer_Control0 = m_FirstPersonPlayer.FindAction("Control0", throwIfNotFound: true);
            m_FirstPersonPlayer_Control1 = m_FirstPersonPlayer.FindAction("Control1", throwIfNotFound: true);
            // FirstPersonHRI
            m_FirstPersonHRI = asset.FindActionMap("FirstPersonHRI", throwIfNotFound: true);
            m_FirstPersonHRI_Toggle = m_FirstPersonHRI.FindAction("Toggle", throwIfNotFound: true);
            m_FirstPersonHRI_Grab = m_FirstPersonHRI.FindAction("Grab", throwIfNotFound: true);
            m_FirstPersonHRI_Drag = m_FirstPersonHRI.FindAction("Drag", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // FirstPersonPlayer
        private readonly InputActionMap m_FirstPersonPlayer;
        private List<IFirstPersonPlayerActions> m_FirstPersonPlayerActionsCallbackInterfaces = new List<IFirstPersonPlayerActions>();
        private readonly InputAction m_FirstPersonPlayer_Move;
        private readonly InputAction m_FirstPersonPlayer_Look;
        private readonly InputAction m_FirstPersonPlayer_Jump;
        private readonly InputAction m_FirstPersonPlayer_Action0;
        private readonly InputAction m_FirstPersonPlayer_Action1;
        private readonly InputAction m_FirstPersonPlayer_Control0;
        private readonly InputAction m_FirstPersonPlayer_Control1;
        public struct FirstPersonPlayerActions
        {
            private @PlayerControls m_Wrapper;
            public FirstPersonPlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_FirstPersonPlayer_Move;
            public InputAction @Look => m_Wrapper.m_FirstPersonPlayer_Look;
            public InputAction @Jump => m_Wrapper.m_FirstPersonPlayer_Jump;
            public InputAction @Action0 => m_Wrapper.m_FirstPersonPlayer_Action0;
            public InputAction @Action1 => m_Wrapper.m_FirstPersonPlayer_Action1;
            public InputAction @Control0 => m_Wrapper.m_FirstPersonPlayer_Control0;
            public InputAction @Control1 => m_Wrapper.m_FirstPersonPlayer_Control1;
            public InputActionMap Get() { return m_Wrapper.m_FirstPersonPlayer; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(FirstPersonPlayerActions set) { return set.Get(); }
            public void AddCallbacks(IFirstPersonPlayerActions instance)
            {
                if (instance == null || m_Wrapper.m_FirstPersonPlayerActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_FirstPersonPlayerActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Action0.started += instance.OnAction0;
                @Action0.performed += instance.OnAction0;
                @Action0.canceled += instance.OnAction0;
                @Action1.started += instance.OnAction1;
                @Action1.performed += instance.OnAction1;
                @Action1.canceled += instance.OnAction1;
                @Control0.started += instance.OnControl0;
                @Control0.performed += instance.OnControl0;
                @Control0.canceled += instance.OnControl0;
                @Control1.started += instance.OnControl1;
                @Control1.performed += instance.OnControl1;
                @Control1.canceled += instance.OnControl1;
            }

            private void UnregisterCallbacks(IFirstPersonPlayerActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Look.started -= instance.OnLook;
                @Look.performed -= instance.OnLook;
                @Look.canceled -= instance.OnLook;
                @Jump.started -= instance.OnJump;
                @Jump.performed -= instance.OnJump;
                @Jump.canceled -= instance.OnJump;
                @Action0.started -= instance.OnAction0;
                @Action0.performed -= instance.OnAction0;
                @Action0.canceled -= instance.OnAction0;
                @Action1.started -= instance.OnAction1;
                @Action1.performed -= instance.OnAction1;
                @Action1.canceled -= instance.OnAction1;
                @Control0.started -= instance.OnControl0;
                @Control0.performed -= instance.OnControl0;
                @Control0.canceled -= instance.OnControl0;
                @Control1.started -= instance.OnControl1;
                @Control1.performed -= instance.OnControl1;
                @Control1.canceled -= instance.OnControl1;
            }

            public void RemoveCallbacks(IFirstPersonPlayerActions instance)
            {
                if (m_Wrapper.m_FirstPersonPlayerActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IFirstPersonPlayerActions instance)
            {
                foreach (var item in m_Wrapper.m_FirstPersonPlayerActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_FirstPersonPlayerActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public FirstPersonPlayerActions @FirstPersonPlayer => new FirstPersonPlayerActions(this);

        // FirstPersonHRI
        private readonly InputActionMap m_FirstPersonHRI;
        private List<IFirstPersonHRIActions> m_FirstPersonHRIActionsCallbackInterfaces = new List<IFirstPersonHRIActions>();
        private readonly InputAction m_FirstPersonHRI_Toggle;
        private readonly InputAction m_FirstPersonHRI_Grab;
        private readonly InputAction m_FirstPersonHRI_Drag;
        public struct FirstPersonHRIActions
        {
            private @PlayerControls m_Wrapper;
            public FirstPersonHRIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Toggle => m_Wrapper.m_FirstPersonHRI_Toggle;
            public InputAction @Grab => m_Wrapper.m_FirstPersonHRI_Grab;
            public InputAction @Drag => m_Wrapper.m_FirstPersonHRI_Drag;
            public InputActionMap Get() { return m_Wrapper.m_FirstPersonHRI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(FirstPersonHRIActions set) { return set.Get(); }
            public void AddCallbacks(IFirstPersonHRIActions instance)
            {
                if (instance == null || m_Wrapper.m_FirstPersonHRIActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_FirstPersonHRIActionsCallbackInterfaces.Add(instance);
                @Toggle.started += instance.OnToggle;
                @Toggle.performed += instance.OnToggle;
                @Toggle.canceled += instance.OnToggle;
                @Grab.started += instance.OnGrab;
                @Grab.performed += instance.OnGrab;
                @Grab.canceled += instance.OnGrab;
                @Drag.started += instance.OnDrag;
                @Drag.performed += instance.OnDrag;
                @Drag.canceled += instance.OnDrag;
            }

            private void UnregisterCallbacks(IFirstPersonHRIActions instance)
            {
                @Toggle.started -= instance.OnToggle;
                @Toggle.performed -= instance.OnToggle;
                @Toggle.canceled -= instance.OnToggle;
                @Grab.started -= instance.OnGrab;
                @Grab.performed -= instance.OnGrab;
                @Grab.canceled -= instance.OnGrab;
                @Drag.started -= instance.OnDrag;
                @Drag.performed -= instance.OnDrag;
                @Drag.canceled -= instance.OnDrag;
            }

            public void RemoveCallbacks(IFirstPersonHRIActions instance)
            {
                if (m_Wrapper.m_FirstPersonHRIActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IFirstPersonHRIActions instance)
            {
                foreach (var item in m_Wrapper.m_FirstPersonHRIActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_FirstPersonHRIActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public FirstPersonHRIActions @FirstPersonHRI => new FirstPersonHRIActions(this);
        public interface IFirstPersonPlayerActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnAction0(InputAction.CallbackContext context);
            void OnAction1(InputAction.CallbackContext context);
            void OnControl0(InputAction.CallbackContext context);
            void OnControl1(InputAction.CallbackContext context);
        }
        public interface IFirstPersonHRIActions
        {
            void OnToggle(InputAction.CallbackContext context);
            void OnGrab(InputAction.CallbackContext context);
            void OnDrag(InputAction.CallbackContext context);
        }
    }
}
